### ISSUE TITLE
steps to compile resume.tex

### ISSUE THREAD

**Issue by rihenperry** [jez/resume#1]
Hi there,
what are the steps required to compile resume.tex? I already have xelatex template engine and xetex running.I am not able to get desired output by simply running `xelatex resume.tex`. It ends up broken.

**Comment by jez** [comment]
That should work. I'd verify that the command works as you think it does. If it's installed correctly, you should be able to clone the repo and run `make`. Keep in mind that it won't suffice to just have downloaded the `*.tex` file; you have to have the whole repo cloned. 

You might also want to check out the [Makefile](https://github.com/jez/resume/blob/gh-pages/Makefile).

**Comment by rihenperry** [comment]
@jez I have the whole repo. cloned.why should I run make? and what do you mean by "correctly installed"?

**Comment by rihenperry** [comment]
@jez here is the following output to make command:-

rihbyne:resume/ (gh-pages✗) $ make                                                                                                                                                      [2:10:29]
xelatex -interaction nonstopmode resume.tex
This is XeTeX, Version 3.1415926-2.5-0.9999.3 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./resume.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 2 languages loaded.
(./deedy-resume-openfont.cls
Document Class: deedy-resume-openfont 2014/04/30 CV class
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg)
(/usr/share/texlive/texmf-dist/tex/xelatex/xetex-def/xetex.def)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/dvipsnam.def))
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hxetex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/stringenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))

! LaTeX Error: File `titlesec.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 

l.16 \usepackage
                [absolute]{textpos}^^M
No pages of output.
Transcript written on resume.log.
make: **\* [resume.pdf] Error 1

**Comment by jez** [comment]
I'm not sure what this error is. `titlesec.sty` is a file that I have on my local machine at `/usr/local/texlive/2014/texmf-dist/tex/latex/titlesec/titlesec.sty`, a file which was shipped with my default installation of LaTeX. I'd recommend verifying that your installation of LaTeX is correct. Unfortunately, I'm on OS X, so I can't really help you debug this issue.

One thing I do note is that you seem to be using a TeX distribution from 2013. Perhaps consider upgrading.
